### PR TITLE
fixed dx date rule and added testing

### PR DESCRIPTION
**Pull request by agsong**

### CODE REVIEW

**Comment by depryf** [comment]
You comment in the issue says that you fixed the issue for DX date and DOLC, but I see no change at all for DOLC. Is that intended?

Also, can you please update the CHANGELOG.md, please add a new section on the top "Changes in version 0.4" and add an entry with a short description of your changes. Thanks.

**Comment by agsong** [comment]
Well DOLC rule just takes the DX date from the tumor with no other logic. I just meant that fixing DX date will also fix any DOLC future dates as well.

**Comment by depryf** [comment]
OK, that makes sense. Please fix the changelog file and I will merge these changes.

**Comment by depryf** [comment]
It looks like you updated the changelog file on master. I am surprised you were able to, but whatever. It's OK this time since I am about to merge this, but please make sure to push to the correct branch.

**Pull request merged**
